### ISSUE TITLE
NTU_CV.hdf5？

### ISSUE THREAD

**Issue by ilikeokoge** [FanyangMeng/Sample-Fusion-Network-An-End-to-End-Data-Augmentation-Network#1]
Thank you for great work!
I try to do your code on NTU RGB+D.
But I don't do your code because I don't have NTU_CV.hdf5 in your code.
Do you share it? or Do you explain what kind of data(I have an original dataset.).

**Comment by preksha12** [comment]
You can see other repositories for extracting hdf5 files for NTU dataset. I have one query is this code complete as I am trying to run it and it is training from 6 days. I am not able to see testing accuracy too.

**Comment by FanyangMeng** [comment]
The processed data can be obtained by Baidu Cloud:
    Link：https://pan.baidu.com/s/1hdrkaiAlctPdIX7hwgKmFg
     Extraction Code ：8jbp
     For a given skeleton data x in the NTU RGB+D dataset, the data preprocessing is as follows：
       1), the size of x is reshaped to N×150. 
            For a single-person action (N×25×3), x will be copied and concat to N×25×3×2, and then reshaped to N×150; For  a two-person mutual action (N×25×3×2), x will be reshaped to N×150 directly.
      2), resize N×150 to 100×150

**Comment by FanyangMeng** [comment]
> You can see other repositories for extracting hdf5 files for NTU dataset. I have one query is this code complete as I am trying to run it and it is training from 6 days. I am not able to see testing accuracy too.

Can you provide more details?I have no problem
![image](https://user-images.githubusercontent.com/13998104/82171340-9c03e100-98f9-11ea-8f93-2d56e5a2f06f.png)

**Comment by preksha12** [comment]
Hello,
Thank you so much for your reply.

Actually I trained the network on CPU. It was training for 6 days. Result was also very low which is 0.006% almost for SFN_05 or SFN_0 and SFN_1 so what can be problem?

**Comment by FanyangMeng** [comment]
> Hello,
> Thank you so much for your reply.
> 
> Actually I trained the network on CPU. It was training for 6 days. Result was also very low which is 0.006% almost for SFN_05 or SFN_0 and SFN_1 so what can be problem?


  180：“ model_SFN = SFNNet(input_dim,hind_dim,args.SFN_layers).cuda()
 181： model_HAR = HARNet(input_dim,args.Output_dim,args.HAR_layers,args.Output_classnum).cuda()”
modified to
 “model_SFN = SFNNet(input_dim,hind_dim,args.SFN_layers).to(device)
    model_HAR = HARNet(input_dim,args.Output_dim,args.HAR_layers,args.Output_classnum).to(device)”

**Comment by preksha12** [comment]
Can I not run it on CPU?

**Comment by FanyangMeng** [comment]
I updated the code, you can try again.

**Comment by FanyangMeng** [comment]
I updated the code, you can try again

发送自 Windows 10 版邮件应用

发件人: preksha12
发送时间: 2020年5月18日 16:27
收件人: FanyangMeng/Sample-Fusion-Network
抄送: fanyang meng; Comment
主题: Re: [FanyangMeng/Sample-Fusion-Network] NTU_CV.hdf5？ (#1)

Can I not run it on CPU?

**Comment by preksha12** [comment]
Thank you,
 Can you please send NTU data in google drive or zip file?

**Comment by preksha12** [comment]
> The processed data can be obtained by Baidu Cloud:
> Link：https://pan.baidu.com/s/1hdrkaiAlctPdIX7hwgKmFg
> Extraction Code ：8jbp
> For a given skeleton data x in the NTU RGB+D dataset, the data preprocessing is as follows：
> 1), the size of x is reshaped to N×150.
> For a single-person action (N×25×3), x will be copied and concat to N×25×3×2, and then reshaped to N×150; For a two-person mutual action (N×25×3×2), x will be reshaped to N×150 directly.
> 2), resize N×150 to 100×150

Can you send it in zip file as this file is not accessible
